"""ReprForge: physical-plan compilation for multimodal RAG indexes."""

from .adapters import (
    AdapterDependencyScope,
    BoundaryState,
    DocumentEncoderAdapter,
    inspect_adapter_tensor_keys,
)
from .execution import (
    CoalescedState,
    CompilerConfig,
    PageAssignment,
    ReprForgeCompiler,
    apply_assignment,
    assign_topology_anchored,
    coalesce_hidden_states,
    topology_anchors,
)
from .indexing import (
    CompactIndex,
    GenerationArtifact,
    GenerationManifest,
    IndexManifest,
    SearchResult,
    load_index,
    maxsim_score,
    normalize_rows,
    publish_generation,
    resolve_active_generation,
    save_index,
    seal_generation,
    validate_generation,
)
from .planning import (
    BackboneProfile,
    CompilePlan,
    ComponentEquivalence,
    ComponentOutputFingerprint,
    MaterializationDecision,
    MaterializationOption,
    UpdateRoute,
    UpdateScenario,
    VersionManifest,
    certify_component_equivalence,
    certify_component_fingerprints,
    choose_materializations,
    evaluate_materializations,
    fingerprint_component_outputs,
    plan_topology_anchored,
)
from .runtime import (
    Lifecycle,
    LifecycleDecision,
    WorkloadProfile,
    choose_lifecycle,
    refine_candidates,
)

__all__ = [
    "AdapterDependencyScope",
    "BackboneProfile",
    "BoundaryState",
    "CoalescedState",
    "CompactIndex",
    "CompilePlan",
    "ComponentEquivalence",
    "ComponentOutputFingerprint",
    "CompilerConfig",
    "DocumentEncoderAdapter",
    "GenerationArtifact",
    "GenerationManifest",
    "IndexManifest",
    "Lifecycle",
    "LifecycleDecision",
    "MaterializationDecision",
    "MaterializationOption",
    "PageAssignment",
    "ReprForgeCompiler",
    "SearchResult",
    "UpdateRoute",
    "UpdateScenario",
    "VersionManifest",
    "certify_component_equivalence",
    "certify_component_fingerprints",
    "WorkloadProfile",
    "apply_assignment",
    "assign_topology_anchored",
    "choose_lifecycle",
    "choose_materializations",
    "coalesce_hidden_states",
    "evaluate_materializations",
    "fingerprint_component_outputs",
    "inspect_adapter_tensor_keys",
    "load_index",
    "maxsim_score",
    "normalize_rows",
    "plan_topology_anchored",
    "publish_generation",
    "refine_candidates",
    "resolve_active_generation",
    "save_index",
    "seal_generation",
    "topology_anchors",
    "validate_generation",
]

__version__ = "0.4.0"
